### ISSUE TITLE
fileUpload not work in any platform 

### ISSUE THREAD

**Issue by cherifAlimat** [teamstudio/xcontrols-domino#316] opened 2015-03-20 15:29 UTC
I have inserted a fileUpload control in the PersonEdit.xsp. It appear. Browse file for upload work. But when i save the file is not saved.

I have inserted these lines between the Phone and the Details :
![fileupload](https://cloud.githubusercontent.com/assets/11573806/6754645/2655287e-cf1e-11e4-9419-a1a6af416050.jpg)

I have also tried to insert PhotoCard and other case UnpBootPhotoUpload, but it don't work.
Is there an issue ?

**Comment by whitemx** [comment] 2015-03-20 15:38
Duplicate of #315

**Closed by whitemx** 2015-03-20 15:38 UTC
Labels: duplicate
