### ISSUE TITLE
Add server property to UnpBootFlatView (and other controls) so data can be received from other DBs on different servers

### ISSUE THREAD

**Issue by RichSharpe** [teamstudio/xcontrols-domino#281] opened 2015-01-14 19:36 UTC
Currently the controls assume all apps are on the same server. Can we include functionality to access docs and views from other servers. 
This is a real use-case requirement where an existing 'Notes only' app is behind the firewall and to access it via a web browser and new app containing UI is in the DMZ using the existing app as a look-up for data.

**Comment by whitemx** [comment] 2015-01-15 08:18
Duplicate of #243

**Closed by whitemx** 2015-01-15 08:18 UTC
Labels: duplicate
