### ISSUE TITLE
A to Z picker

### ISSUE THREAD

**Issue by sives** [teamstudio/xcontrols-domino#295] opened 2015-01-19 14:43 UTC
The A - Z picker in the Categorized List has a glitch on iOS in Unplugged.  When you tap on it, the List view in the left hand pane disappears, if you tap the picker again (or tap in the empty left hand pane) it re-appears.

Also, on Android in Unplugged the picker doesn't seem to work at all.

**Comment by whitemx** [comment] 2015-01-19 20:24
This is a duplicate of #248

**Closed by whitemx** 2015-01-19 20:24 UTC
Labels: duplicate
