### ISSUE TITLE
Editing Card - rich text control

### ISSUE THREAD

**Issue by sives** [teamstudio/xcontrols-domino#260] opened 2014-11-27 15:28 UTC
The current implementation of the Quill editor in the sampler app seems to have a number of issues. Mark L thinks that the origin for these is in the Quill library, which may make the solution difficult. Try for example a simple task: open an existing item, add some text and a bulleted list with a couple of options.

**Comment by edm00se** [comment] 2015-02-19 02:01
My just posted issue #310 may be a duplicate of this.

**Comment by whitemx** [comment] 2015-02-20 14:54
We will be removing the RichTextEditor as part of 1.3.1 until we can find a more stable rich text plugin.

**Comment by edm00se** [comment] 2015-02-23 14:02
This looks to be resoved as part of #279. Matt since it was driven by the unplugged.nsf Max Response Size setting, I might recommend that it be kept in the demo app.

**Comment by whitemx** [comment] 2015-02-24 11:16
Now that we have a reliable fix, we'll reinstate the rich text editor

**Closed** 2015-02-24 11:16 UTC
Labels: bug
